### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by CraigTarling** [pintawebware/cs-cart-module-admin#1]
Hi. I am using CS-CART 4.5.1. I have added the app to the store but it won't install. Says the following:

ErrorOops, something went wrong (Internal Server Error). Please try again.

Any advice? Thanks. Craig

**Comment by kirians** [comment]
Hi Craig

we need see error log in server
can u send me in email ruslan@pinta.com.ua
or write me, i can help you

Best Regards
